#+title: Doom Emacs
#+subtitle: Welcome
#+last_update: 2023-01-27 10:29:39
#+layout: post
#+tags: dev

 * 나의 이맥스 설정은 부팅(?)이 느리다. 이건 명백한 사실. 심할 때는 3분 가까이
   걸리기도 함.
 * 다양한 이맥스 변종 (예: 스페이스맥스) 에 대해 알고는 있었음. 그 중 둠
   이맥스는 테마가 마음에 들어서 개인적으로 고쳐다 쓰고 있었음.
 * 대체 왜 이렇게 부팅이 느린지 검색하다가 [[https://github.com/doomemacs/doomemacs/blob/develop/docs/faq.org#how-does-doom-start-up-so-quickly][요런 글]]을 보게 되었고 홀린듯이 둠
   이맥스에 도전.
 * 그 결과 지금은 마이그레이션에 대해서 아주 만족스러움.

** 내가 이해한 둠 이맥스
 둠 이맥스에 대한 나의 멘탈 모델은 크게 세 가지.
 1. 모던 패키지 매니저. 이맥스의 기본 패키지 로더를 최적화해서 부팅 속도를
    비약적으로 높여주고, 다양하고 편리한 매크로를 제공해서 패키지 별로 설정을
    아주 편리하게 해줌 (=use-package= 보다 더 편함!) [[https://github.com/doomemacs/doomemacs/blob/develop/docs/faq.org#why-such-a-complicated-package-management-system][둠 패키지 관리 시스템의 철학]]
 2. 메이저 패키지 큐레이터. 둠 이맥스의 철학 중 하나인 *Reproducibility* 를 위해서
    많이 쓰이는 패키지는 자체적으로 커밋을 고정시켜서 관리하고 있고, 이걸 /모듈/
    이라는 이름으로 관리하고 있다. 덕분에 나도 잘 모르던 메이저 패키지를
    엄청나게 많이 알게 되었고 덕분에 지금 내 이맥스는 엄청나게 진화했다.
 3. 최첨단 이맥스 프레임워크. 두 가지를 내포하고 있는데: *최첨단* 과 *프레임워크*
    이다. *최첨단* 이므로 아직까지 대응하는 버전, OS 이슈 등이 있어서 몇몇
    설정(특히 모듈)의 경우 자주 깨져서 이맥스가 먹통이 되는 사례가 발생한다
    (...) . 따라서 이맥스 뉴비에게 추천하기에는 조금 애매한 부분이 있다. 반면에
    *프레임워크* 인만큼, 기존의 =.emacs.d= 는 둠이 관리해주고 우리는 =.doom.d= 에서
    내가 쓸 패키지와 추가 설정만을 하면 되므로, 기존의 엄청나게 자유롭던
    =.emacs.d= 관리에서 벗어나 마음이 홀가분해진다. 따라서 이맥스 뉴비에게도
    추천하기 좋은 부분이 있다(?). 이런 모순적인 부분이 재밌다.
